In [129]:
import numpy as np

In [130]:
A = np.array([[2, 0, 1, -3, -2],[0, 2, -3, -3, -2],[1, 2, 1, 3, -2],[-1, 1, 3, 2, -1],[1, 0, 1, -1, 1],[2, 3, -1, 1, -2],
             [-2, 3, -3, 3, 2],[-2, -2, 2, 3, -2],[-2, -3, 1, -2, -3],[-3, 2, 0, -1, -2]]).T

In [131]:
A = A.astype(float)

In [132]:
print(A)

[[ 2.  0.  1. -1.  1.  2. -2. -2. -2. -3.]
 [ 0.  2.  2.  1.  0.  3.  3. -2. -3.  2.]
 [ 1. -3.  1.  3.  1. -1. -3.  2.  1.  0.]
 [-3. -3.  3.  2. -1.  1.  3.  3. -2. -1.]
 [-2. -2. -2. -1.  1. -2.  2. -2. -3. -2.]]


In [133]:
m = np.sum(A,axis=1)/10

In [134]:
for i in range(5):
    for j in range(10):
        A[i][j] = A[i][j]-m[i]

In [135]:
print(A)

[[ 2.4  0.4  1.4 -0.6  1.4  2.4 -1.6 -1.6 -1.6 -2.6]
 [-0.8  1.2  1.2  0.2 -0.8  2.2  2.2 -2.8 -3.8  1.2]
 [ 0.8 -3.2  0.8  2.8  0.8 -1.2 -3.2  1.8  0.8 -0.2]
 [-3.2 -3.2  2.8  1.8 -1.2  0.8  2.8  2.8 -2.2 -1.2]
 [-0.7 -0.7 -0.7  0.3  2.3 -0.7  3.3 -0.7 -1.7 -0.7]]


In [136]:
sigma = np.dot(A,A.T)/10
print(sigma)

[[ 3.04  0.82 -0.02 -0.82 -0.12]
 [ 0.82  3.76 -2.16  1.04  1.04]
 [-0.02 -2.16  3.56  0.76 -0.84]
 [-0.82  1.04  0.76  5.56  1.16]
 [-0.12  1.04 -0.84  1.16  2.21]]


In [137]:
eigen_vals, eigen_vecs = np.linalg.eig(sigma)
index=np.argsort(eigen_vals)
n_index=index[-1:-3:-1]
n_eigenVec=eigen_vecs[:, n_index]
n_eigenVals=eigen_vals[n_index]

In [138]:
print(n_eigenVec)

[[-0.02625442  0.29809153]
 [ 0.57873744  0.39493632]
 [-0.32862419 -0.58025264]
 [ 0.65356276 -0.64618454]
 [ 0.35949345  0.03031732]]


In [139]:
print(n_eigenVals)

[6.76978985 5.93067614]


In [140]:
projection=np.dot(n_eigenVec.T,A)

In [141]:
print(projection)

[[-3.13194616 -0.60746566  1.97315969  0.4956134  -0.72008587  1.87576557
   5.38313097 -0.591651   -4.46907149 -0.20744945]
 [ 1.98183693  4.49653708 -1.40348923 -2.87861204  0.48232827  1.74241301
   0.53945236 -4.45776178 -1.07184006  0.56913546]]
